package Temp;

/**
 * @author Shegufta Ahsan
 * @project SafeHomeFramework
 * @date 07-Sep-19
 * @time 7:50 AM
 */
public enum MEASUREMENT_TYPE
{
    WAIT_TIME,
    LATENCY_OVERHEAD,
    STRETCH_RATIO,
    PARALLEL,
    ISVLTN4_CMD_TO_COMMIT_COLLISION_TIMESPAN_PRCNT,
    ISVLTN3_CMD_VIOLATION_PRCNT_PER_RTN,
    ISVLTN2_VIOLATED_RTN_PRCNT,
    ISVLTN1_PER_RTN_COLLISION_COUNT,
    ORDDER_MISMATCH,
    ORDERR_MISMATCH_BUBBLE,
    ABORT_RATE,
    RECOVERY_CMD,
    DEVICE_UTILIZATION
}