package Temp;

/**
 * @author Shegufta Ahsan
 * @project SafeHomeFramework
 * @date 07-Sep-19
 * @time 7:50 AM
 */
public enum MEASUREMENT_TYPE
{
    WAIT_TIME,
    LATENCY_OVERHEAD,
    STRETCH_RATIO,
    PARALLEL,
    //ISOLTN_VIOLTN_AMONG_LINEAGES,
    //ISOLTN_VIOLTN_AMONG_ROUTINES,
    ISVLTN_PER_RTN_VICTIM_CMD_PRCNT,
    ISVLTN_VICTIM_RTN_PRCNT_PER_RUN,
    ISVLTN_PER_VICTIM_RTN_ATTCKER_COUNT,
    ORDDER_MISMATCH,
    ABORT_RATE,
    RECOVERY_CMD,
    DEVICE_UTILIZATION
}